AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members

Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python2.7
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            cors: true
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
  GetAllItemsInDynamoTable:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get_all_items_in_db
      Runtime: python2.7
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /getAllItems
            Method: get
        PostEvent:
          Type: Api
          Properties:
            Path: /getAllItems
            Method: post
  AddItemToDynamoDb:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.add_item_to_dynamo_db
      Runtime: python2.7
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /addItem
            Method: post
